[tool.poetry]
name = "openbb-intrinio"
version = "1.3.2"
description = "Intrinio extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_intrinio" }]

[tool.poetry.dependencies]
python = "^3.9"
requests-cache = "^1.1.0"
openbb-core = "^1.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
intrinio = "openbb_intrinio:intrinio_provider"
