[tool.poetry]
name = "openbb-cboe"
version = "1.3.3"
description = "CBOE extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_cboe" }]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp-client-cache = "^0.11.0"
aiosqlite = "^0.20.0"
openbb-core = "^1.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
cboe = "openbb_cboe:cboe_provider"
