[tool.poetry]
name = "openbb-technical"
version = "1.3.3"
description = "Technical Analysis extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_technical" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"  # scipy forces python <4.0 explicitly
openbb-core = "^1.3.4"
scipy = "^1.10.1"
statsmodels = "^0.14.0"
scikit-learn = "^1.5.0"
pandas-ta = "^0.3.14b"
numpy = "^1"  # pin until pandas-ta is updated to support numpy 2.0

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
technical = "openbb_technical.technical_router:router"

[tool.poetry.plugins."openbb_charting_extension"]
technical = "openbb_technical.technical_views:TechnicalViews"
