[tool.poetry]
name = "openbb-tradier"
version = "1.2.3"
description = "Tradier Provider Extension for the OpenBB Platform"
authors = ["OpenBB <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_tradier" }]

[tool.poetry.dependencies]
python = "^3.9"
openbb-core = "^1.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
tradier = "openbb_tradier:tradier_provider"
