[tool.poetry]
name = "openbb-oecd"
version = "1.3.3"
description = "OECD extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_oecd" }]

[tool.poetry.dependencies]
python = "^3.9"
openbb-core = "^1.3.4"
urllib3 = ">1.26.16"
defusedxml = "^0.8.0rc2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
oecd = "openbb_oecd:oecd_provider"
