[tool.poetry]
name = "openbb-polygon"
version = "0.1.0a2"
description = "Polygon extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_polygon" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^0.1.0a2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
polygon = "openbb_polygon:polygon_provider"
