[tool.poetry]
name = "openbb-fred"
version = "0.0.0a1"
description = ""
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_fred" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-provider = {version = "^0.0.0a1", source = "test-pypi"}

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
fred = "openbb_fred:fred_provider"
