[tool.poetry]
name = "openbb-ecb"
version = "1.3.3"
description = "ECB extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_ecb" }]

[tool.poetry.dependencies]
python = "^3.9"
openbb-core = "^1.3.4"
xmltodict = "^0.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
ecb = "openbb_ecb:ecb_provider"
