[tool.poetry]
name = "openbb-news"
version = "0.0.0a0"
description = ""
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_news" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = {version = "0.0.0a1", source = "test-pypi"}

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
news = "openbb_news.news_router:router"
