[tool.poetry]
name = "openbb-cboe"
version = "0.0.0a1"
description = "CBOE integration for OpenBB SDK"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_cboe" }]

[tool.poetry.dependencies]
python = "^3.8"
requests-cache = "^1.1.0"
openbb-core = {version = "^0.0.0a5", source = "test-pypi"}

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
cboe = "openbb_cboe:cboe_provider"
