version: '3.8'
services:
  poetry:
    environment:
        DISPLAY: host.docker.internal:0.0
    volumes:
      - ~/OpenBBUserData:/home/python/OpenBBUserData
      - ~/.openbb_terminal:/home/python/.openbb_terminal
    platform: linux/amd64
    image: ghcr.io/openbb-finance/openbbterminal/poetry:1.9.1
    stdin_open: true # docker run -i
    tty: true        # docker run -t