[tool.poetry]
name = "openbb-fmp"
version = "0.1.0"
description = "FMP extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_fmp" }]

[tool.poetry.dependencies]
python = "^3.8"
requests-cache = "^1.1.0"
openbb-core = { path = "../../sdk/core" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
fmp = "openbb_fmp:fmp_provider"
