[tool.poetry]
name = "openbb-fmp"
version = "0.0.0a2"
description = "FMP integration for OpenBB SDK"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_fmp" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = {version = "^0.0.0a5", source = "test-pypi"}

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
fmp = "openbb_fmp:fmp_provider"
