[tool.poetry]
name = "openbb-wsj"
version = "0.1.0a4"
description = "wsj extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_wsj" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^0.1.0a5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
wsj = "openbb_wsj:wsj_provider"
