[tool.poetry]
name = "openbb-tiingo"
version = "1.1.1"
description = "Tiingo extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_tiingo" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
tiingo = "openbb_tiingo:tiingo_provider"
