[tool.poetry]
name = "openbb-finviz"
version = "1.1.2"
description = "Finviz extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_finviz" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^1.2.4"
finvizfinance = "0.14.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
finviz = "openbb_finviz:finviz_provider"
