[tool.poetry]
name = "openbb-government-us"
version = "1.3.3"
description = "US Government Data Extension for OpenBB"
authors = ["OpenBB <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_government_us" }]

[tool.poetry.dependencies]
python = "^3.9"
openbb-core = "^1.3.4"
random-user-agent = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
government_us = "openbb_government_us:government_us_provider"
