[tool.poetry]
name = "openbb-government-us"
version = "1.0.0"
description = "US Government Data Extension for OpenBB"
authors = ["OpenBB <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_government_us" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
government_us = "openbb_government_us:government_us_provider"
