[tool.poetry]
name = "openbb-economy"
version = "0.0.0a3"
description = "Economy extension for OpenBB SDK"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_economy" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = {version = "^0.0.0a7", source = "test-pypi"}

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
economy = "openbb_economy.economy_router:router"
