[tool.poetry]
name = "openbb-federal-reserve"
version = "1.3.2"
description = "US Federal Reserve Data Extension for OpenBB"
authors = ["OpenBB <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_federal_reserve" }]

[tool.poetry.dependencies]
python = "^3.9"
openbb-core = "^1.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
federal_reserve = "openbb_federal_reserve:federal_reserve_provider"
