[tool.poetry]
name = "openbb-fred"
version = "1.2.0"
description = "FRED extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_fred" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^1.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
fred = "openbb_fred:fred_provider"
