[tool.poetry]
name = "openbb-benzinga"
version = "0.1.0a2"
description = "Benzinga extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_benzinga" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^0.1.0a2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
benzinga = "openbb_benzinga:benzinga_provider"
