[tool.poetry]
name = "openbb-seeking-alpha"
version = "1.3.3"
description = "Seeking Alpha extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_seeking_alpha" }]

[tool.poetry.dependencies]
python = "^3.9"
openbb-core = "^1.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
seeking_alpha = "openbb_seeking_alpha:seeking_alpha_provider"
