name: Build & Release

env:
  OPENBB_ENABLE_QUICK_EXIT: true
  OPENBB_LOG_COLLECT: false
  OPENBB_USE_PROMPT_TOOLKIT: false
  PIP_DEFAULT_TIMEOUT: 100
  PYTHONNOUSERSITE: 1

on:
  push:
    branches:
      - release/*
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write

jobs:
  trigger-windows-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Windows Build
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: windows10_build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion-timeout: 2h

  trigger-macos-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Intel & M1 MacOs Build
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: macos-build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion-timeout: 2h

  trigger-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docker Build
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: docker-build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
