name: Build and publish release

env:
  OPENBB_ENABLE_QUICK_EXIT: true
  OPENBB_LOG_COLLECT: false
  OPENBB_USE_ION: false
  OPENBB_USE_PROMPT_TOOLKIT: false
  PIP_DEFAULT_TIMEOUT: 100
  PYTHONNOUSERSITE: 1

on:
  push:
    branches:
      - release/*
      - feature/*
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: 
  actions: write

jobs:
  trigger-windows-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Windows Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: windows10_build.yml
  
  trigger-macos-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Windows Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: m1_macos_build.yml
  
  trigger-intel-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Windows Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: intel_macos_build.yml
  
  trigger-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Windows Build
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: docker.yml
