name: Check issue template

on:
  issues:
    types: [opened]

jobs:
  check-template:
    runs-on: ubuntu-latest

    steps:
    - name: Check issue template
      id: check-template
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = context.payload.issue;
          const templates = ["bug_report.md", "enhancement.md", "feature_request.md"];
          let templateMatched = false;
          for (const template of templates) {
            const templateContent = await github.repos.getContents({
              owner: 'jmaslek',
              repo: context.repo.repo,
              path: `.github/${template}`
            });
            const content = Buffer.from(issue.body, 'base64').toString();
            if (content === templateContent.data.content) {
              console.log(`Issue template ${template} has not been changed.`);
              templateMatched = true;
              break;
            }
          }
          if (!templateMatched) {
            console.log('Issue template has been changed.');
          } else {
            const params = {
              owner: 'jmaslek',
              repo: context.repo.repo,
              issue_number: issue.number,
              state: 'closed'
            }
            await github.issues.update(params);
          }
