name: Release Drafter

on: workflow_dispatch

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
