name: Release Drafter

on: 
  workflow_dispatch:
    inputs:
      release_pr_number:
        description: 'Release PR Number'
        required: true
        default: ''
      tag:
        description: 'Tag for release (manual input)'
        required: true
        default: ''

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“Ÿ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ“ Release Drafter
        id: release-drafter
        uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ’¾ Save Changelog
        run: |
          printf '%s\n' "${{ steps.release-drafter.outputs.body }}" > CHANGELOG.md
          cat CHANGELOG.md

      # - name: ðŸ§¬ Process Changelog
      #   run: |
      #     python process_changelog.py CHANGELOG.md ${{ github.event.inputs.release_pr_number }}

      # - name: ðŸ›« Create Release
      #   uses: mikepenz/action-gh-release@v1
      #   with:
      #     body_path: "CHANGELOG.md"
      #     tag_name: ${{ github.event.inputs.tag }}
      #     prerelease: false
      #     draft: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}