name: Release Drafter

on: 
  workflow_dispatch:
    inputs:
      release_pr_number:
        description: 'Release PR Number'
        required: true
        default: ''

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“Ÿ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ“ Release Drafter
        id: release-drafter
        uses: release-drafter/release-drafter@v5.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ’¾ Save Changelog
        run: |
          echo "${{ steps.release-drafter.outputs.body }}" > CHANGELOG.md

      - name: ðŸ§¬ Process Changelog
        run: |
          python process_changelog.py ${{ github.event.inputs.release_pr_number }}