name: github pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Generate the new documentation
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          - name: Install dependencies
            run: | 
              pip install -r requirements.txt
              pip install 
          - name: Run the script
            run: python website/generate.py

      - name: Commit Documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.87.0'
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        working-directory: ./website
        env:
          BEACON_TOKEN: ${{ secrets.HUGO_ANALYTICS }}
        run: |
          sed -i -e "s/{%BEACON%}/$BEACON_TOKEN/g" themes/hugo-geekdoc/layouts/partials/foot.html
          hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./website/public
