name: Nightly Build on the develop branch

env:
  OPENBB_ENABLE_QUICK_EXIT: true
  OPENBB_LOG_COLLECT: false
  OPENBB_USE_ION: false
  OPENBB_USE_PROMPT_TOOLKIT: false
  PIP_DEFAULT_TIMEOUT: 100
  OPENBB_FILE_OVERWRITE: true
  PYTHONNOUSERSITE: 1

on:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-windows-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Windows Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: windows.yml

  trigger-macos-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Windows Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: m1_macos_build.yml

  trigger-intel-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Windows Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: intel_macos_build.yml
 