name: Platform Release

on:
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]
    branches:
      - develop
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout repository
        uses: actions/checkout@v4
        with:
          # repository: 'OpenBB-finance/OpenBBTerminal'
          # ref: 'develop'
          fetch-depth: 0

      - name: ğŸ—‚ï¸ Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            openbb_platform/**

      - name: ğŸ·ï¸ Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ”„ Build changelog
        id: build_changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: mikepenz/release-changelog-builder-action@v4.1.1
        with:
          configurationJson: "build/configs/configuration_platform.json"
          path: "openbb_platform"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ›« Create Release
        uses: mikepenz/action-gh-release@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
