name: Platform Release

on:
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]
    branches:
      - develop
  # workflow_dispatch:
  #   inputs:
  #     release_type:
  #       description: 'Release type'
  #       required: true
  #       default: 'patch'
  #     tags:
  #       description: 'Tag name'
  #       required: false
  #       default: 'v4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›’ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ—‚ï¸ Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            openbb_platform/**

      - name: ðŸ·ï¸ Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ”„ Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.1
        with:
          configuration: "build/configs/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ›« Create Release
        uses: mikepenz/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate release notes
      #   id: release-notes
      #   run: |
      #     PR_TITLE="${{ github.event.pull_request.title }}"
      #     PR_BODY="${{ github.event.pull_request.body }}"
      #     RELEASE_NOTES="### Changes:\n- $PR_TITLE\n\n### Description:\n$PR_BODY"
      #     echo "notes=$RELEASE_NOTES" >> $GITHUB_ENV

      # - name: Create Release
      #   if: contains(steps.pr-labels.outputs.labels, ' platform v4 bug enhancement')
      #   run: |
      #     RELEASE_NOTES="${{ env.notes }}"
      #     TAG_NAME="v$(date +%Y.%m.%d.%H.%M.%S)"
      #     gh release create "$TAG_NAME" --draft --title "$TAG_NAME" --notes "$RELEASE_NOTES"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
