
name: Windows10 Build ENV
env:
  OPENBB_ENABLE_QUICK_EXIT: true
  OPENBB_LOG_COLLECT: false
  OPENBB_USE_ION: false
  OPENBB_USE_PROMPT_TOOLKIT: false
  PIP_DEFAULT_TIMEOUT: 100
  PYTHONNOUSERSITE: 1
on: workflow_dispatch
jobs:
  Windows-Build:
    name: Windows10 Build ENV
    runs-on: windows-latest
    # Configuring -------------
    steps:
      - name: Setup Windows Git Configuration # This is under the assumption that git is already installed on the system
        run: |
          Set-ItemProperty 'HKLM:\System\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -value 1
          git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Set up Python & Create OpenBB Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/Scripts/activate
          python -m pip install --upgrade pip
          python -m pip install poetry==1.1.13
          python -m pip install setuptools==64.0.2 wheel
          python -m pip install charset_normalizer==2.1.1
          python -m poetry install -E installer -E all
          python -m pip uninstall papermill -y
          python -m pip install git+https://github.com/nteract/papermill.git@main
          python -m PyInstaller build\pyinstaller\terminal.spec --clean
          7z a -tzip dist\OpenBBTerminal.zip dist\OpenBBTerminal

      # Building ------------
      - name: Save Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: OpenBB-Windows10-Build
          path: dist\OpenBBTerminal.zip
